/* This file was generated by r.out.leaflet GRASS GIS module. */

var layerInfos = [
   {title: "step_00", file: "step_00.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
,   {title: "step_04", file: "step_04.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
,   {title: "step_08", file: "step_08.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
,   {title: "step_12", file: "step_12.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
,   {title: "step_16", file: "step_16.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
,   {title: "step_20", file: "step_20.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
,   {title: "step_23", file: "step_23.png", bounds: [[35.52846680, -78.24079905], [36.22545774, -79.27685841]], opacity: 1.0}
];
